name: candy_smash
description: A Flutter app inspired by the popular Candy Crush game.
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: latest
  go_router: latest
  freezed_annotation: latest
  flutter_animate: latest
  json_annotation: latest

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: latest
  freezed: latest
  json_serializable: latest
flutter:
  uses-material-design: true